/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package Hare-1.0 */
#ifndef VERSION_Hare
#define VERSION_Hare "1.0"
#endif /* VERSION_Hare */
#ifndef MIN_VERSION_Hare
#define MIN_VERSION_Hare(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_Hare */

/* package base-4.10.1.0 */
#ifndef VERSION_base
#define VERSION_base "4.10.1.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  10 || \
  (major1) == 4 && (major2) == 10 && (minor) <= 1)
#endif /* MIN_VERSION_base */

/* package QuickCheck-2.10.1 */
#ifndef VERSION_QuickCheck
#define VERSION_QuickCheck "2.10.1"
#endif /* VERSION_QuickCheck */
#ifndef MIN_VERSION_QuickCheck
#define MIN_VERSION_QuickCheck(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  10 || \
  (major1) == 2 && (major2) == 10 && (minor) <= 1)
#endif /* MIN_VERSION_QuickCheck */

/* package mtl-2.2.1 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.1"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_mtl */

/* tool gcc-13.1.6 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "13.1.6"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  13 || \
  (major1) == 13 && (major2) <  1 || \
  (major1) == 13 && (major2) == 1 && (minor) <= 6)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.2.2 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.2.2"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  2 || \
  (major1) == 8 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.2.2 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.2.2"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  2 || \
  (major1) == 8 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.18.1 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.18.1"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  18 || \
  (major1) == 2 && (major2) == 18 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.67 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.67"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.2 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.2"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool runghc-8.2.2 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.2.2"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  2 || \
  (major1) == 8 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "Hare-1.0-8HgU0w26Z2J24N6GkCiSfg-Hare"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "1.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
